### ISSUE TITLE
Running Docker Container

### ISSUE THREAD

**Issue by aghchan** [kluctl/go-embed-python#22]
hello @codablock, 

is it possible to run this golang app with embedded python in a docker container? I've tried both base images of `FROM golang:1.21` and `FROM golang:1.21-alpine`

I'm encountering errors loading the libs `Dynamic loading not supported`

```
Traceback (most recent call last):
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backend/cmd/api/../../pkg/python/musicgen.py", line 4, in <module>
    from gradio_client import Client
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/gradio_client/client.py", line 24, in <module>
    import requests
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/tmp/go-embedded-embedded-python-459120d29c5e870b/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
ImportError: Dynamic loading not supported
```

**Comment by aghchan** [comment]
turns out that I'm somehow dynamically loading the `chardet` package locally and it needs to be explicitly added to the `requirements.txt` for it to work in my docker container
